name: pkl_apps
description: Aplikasi PKL Hummatech
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_storage: ^2.1.1
  http: ^1.1.0
  bot_toast: ^4.1.3
  google_fonts: ^6.1.0
  file_picker: ^6.1.1
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/icons/
    - assets/gif/
