// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_6M4TtBNprOZJ5kx1o-yjBNe9EcrBKqw',
    appId: '1:329770266632:web:e71eff9bffa7cdb343e1bd',
    messagingSenderId: '329770266632',
    projectId: 'pkl-app-25ace',
    authDomain: 'pkl-app-25ace.firebaseapp.com',
    storageBucket: 'pkl-app-25ace.appspot.com',
    measurementId: 'G-3DLM8R7FRB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAKPf6iu_9VNQafJuY498l4mTNS5C3--A',
    appId: '1:329770266632:android:c0d2bdc37a7092ea43e1bd',
    messagingSenderId: '329770266632',
    projectId: 'pkl-app-25ace',
    storageBucket: 'pkl-app-25ace.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVYVeRVLUGhgkKCB0WZs-j0uyzoBKxZT8',
    appId: '1:329770266632:ios:87ff09d9923d7e9143e1bd',
    messagingSenderId: '329770266632',
    projectId: 'pkl-app-25ace',
    storageBucket: 'pkl-app-25ace.appspot.com',
    iosBundleId: 'com.example.pklApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVYVeRVLUGhgkKCB0WZs-j0uyzoBKxZT8',
    appId: '1:329770266632:ios:49e25f5df714856c43e1bd',
    messagingSenderId: '329770266632',
    projectId: 'pkl-app-25ace',
    storageBucket: 'pkl-app-25ace.appspot.com',
    iosBundleId: 'com.example.pklApps.RunnerTests',
  );
}
